Few small fixes to the emergency script.
 * Only print kept/deleted files if something has changed
 * Added a missing '%s' to fix:
    Traceback (most recent call last):
      File "./mm2_emergency-expire-repo", line 114, in <module>
        sys.exit(main())
      File "./mm2_emergency-expire-repo", line 107, in main
        logger.info("Older versions deleted: " % ', '.join(deleted.keys()))
        TypeError: not all arguments converted during string formatting
 * Use same date/time format for logging as the other scripts
 * Removed unused 'debug' option

Signed-off-by: Adrian Reber <adrian@lisas.de>