umdl: fix crash in _get_version_from_path()
Fixes this traceback when a dir does not have an identifyable version
in it, yet we're trying to make a repository for it.  Unclear what dir
is causing this though.

Traceback (most recent call last):
  File "./update-master-directory-list", line 485, in ?
    sys.exit(main())
  File "./update-master-directory-list", line 477, in main
    sync_directories_from_directory(i['path'], i['category'],
  excludes)
  File "./update-master-directory-list", line 446, in
  sync_directories_from_directory
    sync_category_directories(category, category_directories)
  File "./update-master-directory-list", line 339, in
  sync_category_directories
    make_repository(dir, category)
  File "./update-master-directory-list", line 199, in make_repository
    (ver, arch) = guess_ver_arch_from_path(category, path)
  File "./update-master-directory-list", line 85, in
  guess_ver_arch_from_path
    ver = create_version_from_path(category, path)
  File "./update-master-directory-list", line 53, in
  create_version_from_path
    vname = _get_version_from_path(path)
  File "./update-master-directory-list", line 49, in
  _get_version_from_path
    return m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'